# MDPIC Configuration
## Docs: https://github.com/skycity233/MDPIC/README.md
## Source: https://github.com/skycity233/MDPIC

github_username: mchange
repository_name: pic
language: en-US
hotkey: ctrl+b

